service:
  type: NodePort
  nodePort: 30712

consoleService:
  type: NodePort
  nodePort: 30713

rootUser: "admin"
rootPassword: "monarch-operator"

mode: standalone

replicas: 1
persistence:
  enabled: false

extraVolumes:
  - name: data
    hostPath:
      path: /mnt/data/minio
      type: DirectoryOrCreate
extraVolumeMounts:
  - name: data
    mountPath: /data

resources:
  requests:
    memory: 250Mi

buckets:
  - name: monarch-thanos
