apiVersion: v1
kind: Service
metadata:
  name: gnb-metrics-service
  namespace: open5gs
  labels:
    nf: gnb
    app: monarch
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io.scheme: "http"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9090"
spec:
  clusterIP: None
  ports:
    - name: metrics # expose metrics port
      port: 9090
  selector:
    nf: gnb # target gnb pod