fullnameOverride: nssdc

alertmanager:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: true

  thanosService:
    enabled: false

  thanosServiceMonitor:
    enabled: false
    type: NodePort

  thanosServiceExternal:
    enabled: true
    type: NodePort
    nodePort: 30905
    httpNodePort: 30906

  service:
    type: NodePort
    nodePort: 30095

  serviceMonitor:
    interval: "${MONARCH_MONITORING_INTERVAL}"
    selfMonitor: true

  prometheusSpec:
    externalLabels:
      cluster: core

    enableRemoteWriteReceiver: true

    scrapeInterval: "${MONARCH_MONITORING_INTERVAL}"
    serviceMonitorSelectorNilUsesHelmValues: false

    serviceMonitorNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - open5gs
            - monarch

    retention: 5d

    thanos:
      image: quay.io/thanos/thanos:v0.31.0
      objectStorageConfig:
        key: thanos.yaml
        name: thanos-objstore-config

    additionalScrapeConfigs:
      - job_name: "monarch-service"
        scrape_interval: "${MONARCH_MONITORING_INTERVAL}"
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
                - 'open5gs'
                - 'monarch'
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true

    storageSpec:
      volumeClaimTemplate: {}

    additionalVolumes:
      - name: prometheus-nssdc-prometheus-db
        hostPath:
          path: /mnt/data/prometheus
          type: DirectoryOrCreate
    additionalVolumeMounts:
      - name: prometheus-nssdc-prometheus-db
        mountPath: /prometheus

 # turn OFF the built‑in PVC
  persistence:
    enabled: false
