fullnameOverride: nssdc

alertmanager:
  enabled: false

grafana:
  enabled: false

kubeStateMetrics:
  enabled: true

prometheus:
  enabled: true

  server:
    persistentVolume:
      enabled: true

    additionalVolumes:
      - name: prometheus-data
        hostPath:
          path: /mnt/data/prometheus
          type: DirectoryOrCreate
    additionalVolumeMounts:
      - name: prometheus-data
        mountPath: /prometheus

    extraArgs:
      - --storage.tsdb.wal-compression
      - --storage.tsdb.min-block-duration=1m
      - --storage.tsdb.max-block-duration=2m

  thanosService:
    enabled: false

  thanosServiceMonitor:
    enabled: false
    type: NodePort

  thanosServiceExternal:
    enabled: true
    type: NodePort
    nodePort: 30905
    httpNodePort: 30906

  service:
    type: NodePort
    nodePort: 30095

  serviceMonitor:
    interval: "${MONARCH_MONITORING_INTERVAL}"
    selfMonitor: true

  prometheusSpec:
    externalLabels:
      cluster: core

    enableRemoteWriteReceiver: true

    scrapeInterval: "${MONARCH_MONITORING_INTERVAL}"
    serviceMonitorSelectorNilUsesHelmValues: false

    serviceMonitorNamespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - open5gs
            - monarch

    retention: 5d

    thanos:
      image: quay.io/thanos/thanos:v0.31.0
      objectStorageConfig:
        key: thanos.yaml
        name: thanos-objstore-config
      extraArgs:
      - --ship-interval=1m

    additionalScrapeConfigs:
      - job_name: "monarch-service"
        scrape_interval: "${MONARCH_MONITORING_INTERVAL}"
        kubernetes_sd_configs:
          - role: service
            namespaces:
              names:
                - 'open5gs'
                - 'monarch'
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_annotation_prometheus_io_scrape]
            action: keep
            regex: true

    storageSpec:
      volumeClaimTemplate:
        spec:
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 10Gi

