name: Build & Push 5G-Monarch Monioring Manager image

on:
  push:
    branches: [ test ]
    paths:
      - 'monitoring_manager/**'
  workflow_dispatch:

env:
  GHCR_USER: ziyad-mabrouk
  TAG: v1.0.0

jobs:

  build-and-push-monitoring-manager:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    - name: Log in to GHCR
      run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "${{ env.GHCR_USER }}" --password-stdin

    - name: Build monitoring-manager
      run: |
        docker build --tag monitoring-manager:${{ env.TAG }} -f monitoring_manager/Dockerfile ./monitoring_manager

    - name: Tag and push to GHCR
      run: |
        IMAGE_URI=ghcr.io/${{ env.GHCR_USER }}/monitoring-manager:${{ env.TAG }}
        docker tag monitoring-manager:${{ env.TAG }} "$IMAGE_URI"
        docker push "$IMAGE_URI"

    - name: Log out of GHCR
      if: always()
      run: docker logout ghcr.io
